### PR TITLE
Replace base-includes.h with extension.h

### PR DESCRIPTION
**Pull request by leev**
Helps with Issue #31 for compiling with hhvm 3.7.

### CODE REVIEW

**Comment by mcuadros** [comment]
Cannot perform any test over this, If any can test that this is working will be great

**Comment by leev** [comment]
Unfortunately it's still failing to build.  See https://github.com/facebook/hhvm/commit/91e07b951496b5bfbbb189fd5401e9dd5e711c43 for the removal of base-includes.h.

```# make
[ 33%] Building CXX object CMakeFiles/mongo.dir/src/bson.cpp.o
/home/build/mongofill-hhvm/src/bson.cpp: In function ‘HPHP::String HPHP::f_bson_encode_multiple(const HPHP::Array&)’:
/home/build/mongofill-hhvm/src/bson.cpp:62:32: error: variable ‘HPHP::ArrayIter iter’ has initializer but incomplete type
   for (ArrayIter iter(documents); iter; ++iter) {
                                ^
make[2]: *** [CMakeFiles/mongo.dir/src/bson.cpp.o] Error 1
make[1]: *** [CMakeFiles/mongo.dir/all] Error 2
make: *** [all] Error 2```

**Comment by keithk** [comment]
Was able to add this to bson.cpp and get a successful compile. 
```
#include "hphp/runtime/base/array-iterator.h"
```

**Comment by alex-cc** [comment]
@keithk I had to also add the include in encode.cpp in order to compile.

**Comment by leev** [comment]
Thanks guys, I have updated the commit to include those changes.

**Comment by mcuadros** [comment]
Great job! Thanks for the help

**Pull request merged**
