### PR TITLE
Issue#19 Ubuntu 14.04.1 make failing

### PR DESCRIPTION
**Pull request by eeertekin**
### make error
[ 33%] Building CXX object CMakeFiles/mongo.dir/src/encode.cpp.o
/usr/src/mongofill-hhvm/src/encode.cpp: In function ‘void HPHP::objectToBSON(const HPHP::Object&, const char*, bson_t*)’:
/usr/src/mongofill-hhvm/src/encode.cpp:86:36: error: ‘class HPHP::ObjectData’ has no member named ‘getClassName’
   const String& className = value->getClassName();
                                    ^
make[2]: *** [CMakeFiles/mongo.dir/src/encode.cpp.o] Error 1
make[1]: *** [CMakeFiles/mongo.dir/all] Error 2
make: *** [all] Error 2

### hhvm --version
HipHop VM 3.4.2 (rel)
Compiler: tags/HHVM-3.4.2-0-g40d85d7386b3342ab848fc45c6892433c89ef5b2
Repo schema: 13cba877c4300d1d0481b3f40eb128a5115d4e08
Extension API: 20140829

### CODE REVIEW

**Comment by Pomyk** [comment]
That will break compiling with hhvm on master and 3.5 when it gets released (hopefully soon).

**Comment by eeertekin** [comment]
You're right, but it's already broken on stable hhvm release. 

Can you create another branch for hhvm master and for 3.5? It can help.

**Comment by Pomyk** [comment]
Should work now with new and old hhvm.

**Comment by eeertekin** [comment]
Thanks @Pomyk :)

**Pull request closed without merging**
